---
title: Mānoa version of quarto reveal.js clean  
subtitle: A spin on the minimalist and elegant presentation theme
format: clean-revealjs
footer: "URL"
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Bradley McDonnell 
    email: mcdonn@hawaii.edu
    affiliations: University of Hawai‘i at Mānoa
    orcid: 0000-0000-0000-0000
date: last-modified
---


## Example slide

### This is a subtitle

Here we have some [text]{.highlight} that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

# Inverse {.inverse}

Uses [UH Mānoa green](https://www.hawaii.edu/offices/communications/standards/graphics-standards/signatures/) (#024731 hex color )

## Additional theme classes

### Some extra things you can do with the clean theme

[Special classes for emphasis]{.alert}

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #36454F"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col:  #A2B9C6"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/mcdonn/quarto-revealjs-manoa-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here]().


## Summary {#sec-summary}

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presentation
theme. Here are some options to get you started:

Add the theme to an existing project.

```{.bash}
quarto install extension mcdonn/quarto-revealjs-manoa
```

... or, create a new project using this slide deck as a lean template.

```{.bash}
quarto use template mcdonn/quarto-revealjs-manoa
```

... or, create a new project using the demo slide deck as a full template.

```{.bash}
quarto use template mcdonn/quarto-revealjs-manoa-demo
```